
services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    container_name: swap-client-frontend
    ports:
      - "2088:2088"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    command: ["node", ".output/server/index.mjs"]
    restart: unless-stopped
