export type POPUP_NAME =
  | ''
  | 'popup-select-token'
  | 'popup-sell-token'
  | 'popup-review-position'
  | 'popup-review-swap'
  | 'popup-connect'
  | 'popup-add-liquidity'
  | 'popup-confirm-remove'
  | 'popup-confirm-create-liquidity'
