name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          TAG=${{ github.ref_name }}
          docker build -t aniadev9/monchain-swap-client:$TAG .
          docker push aniadev9/monchain-swap-client:$TAG
          docker tag aniadev9/monchain-swap-client:${TAG} aniadev9/monchain-swap-client:latest
          docker push aniadev9/monchain-swap-client:latest
